// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/swarm/v1/swarm.proto

package swarm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_EVENT       MessageType = 1
	MessageType_MESSAGE_TYPE_TEXT        MessageType = 2
	MessageType_MESSAGE_TYPE_BINARY      MessageType = 3
	MessageType_MESSAGE_TYPE_TOOL_CALL   MessageType = 4
	MessageType_MESSAGE_TYPE_TOOL_RESULT MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_EVENT",
		2: "MESSAGE_TYPE_TEXT",
		3: "MESSAGE_TYPE_BINARY",
		4: "MESSAGE_TYPE_TOOL_CALL",
		5: "MESSAGE_TYPE_TOOL_RESULT",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_EVENT":       1,
		"MESSAGE_TYPE_TEXT":        2,
		"MESSAGE_TYPE_BINARY":      3,
		"MESSAGE_TYPE_TOOL_CALL":   4,
		"MESSAGE_TYPE_TOOL_RESULT": 5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_swarm_v1_swarm_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_swarm_v1_swarm_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_swarm_v1_swarm_proto_rawDescGZIP(), []int{0}
}

type MsgEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceAgentId string                 `protobuf:"bytes,3,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	Type          MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=mycelis.swarm.v1.MessageType" json:"type,omitempty"`
	// OneOf for strictly typed payloads
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*MsgEnvelope_Event
	//	*MsgEnvelope_Text
	//	*MsgEnvelope_ToolCall
	//	*MsgEnvelope_ToolResult
	Payload isMsgEnvelope_Payload `protobuf_oneof:"payload"`
	// Trace context for observability
	TraceId string `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId  string `protobuf:"bytes,11,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Team Routing: The logical group (e.g., "marketing", "sensors")
	TeamId string `protobuf:"bytes,14,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// Context: Shared Key-Value state for swarm intelligence (AG2 Pattern)
	SwarmContext  *structpb.Struct `protobuf:"bytes,15,opt,name=swarm_context,json=swarmContext,proto3" json:"swarm_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgEnvelope) Reset() {
	*x = MsgEnvelope{}
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgEnvelope) ProtoMessage() {}

func (x *MsgEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgEnvelope.ProtoReflect.Descriptor instead.
func (*MsgEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_swarm_v1_swarm_proto_rawDescGZIP(), []int{0}
}

func (x *MsgEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MsgEnvelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MsgEnvelope) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *MsgEnvelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *MsgEnvelope) GetPayload() isMsgEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MsgEnvelope) GetEvent() *EventPayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgEnvelope_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *MsgEnvelope) GetText() *TextPayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgEnvelope_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *MsgEnvelope) GetToolCall() *ToolCallPayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgEnvelope_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *MsgEnvelope) GetToolResult() *ToolResultPayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgEnvelope_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *MsgEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *MsgEnvelope) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *MsgEnvelope) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *MsgEnvelope) GetSwarmContext() *structpb.Struct {
	if x != nil {
		return x.SwarmContext
	}
	return nil
}

type isMsgEnvelope_Payload interface {
	isMsgEnvelope_Payload()
}

type MsgEnvelope_Event struct {
	Event *EventPayload `protobuf:"bytes,5,opt,name=event,proto3,oneof"`
}

type MsgEnvelope_Text struct {
	Text *TextPayload `protobuf:"bytes,6,opt,name=text,proto3,oneof"`
}

type MsgEnvelope_ToolCall struct {
	ToolCall *ToolCallPayload `protobuf:"bytes,7,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type MsgEnvelope_ToolResult struct {
	ToolResult *ToolResultPayload `protobuf:"bytes,8,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

func (*MsgEnvelope_Event) isMsgEnvelope_Payload() {}

func (*MsgEnvelope_Text) isMsgEnvelope_Payload() {}

func (*MsgEnvelope_ToolCall) isMsgEnvelope_Payload() {}

func (*MsgEnvelope_ToolResult) isMsgEnvelope_Payload() {}

type EventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // e.g. "sensor.update", "task.complete"
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // Equivalent to Dict[str, Any]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPayload) Reset() {
	*x = EventPayload{}
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPayload) ProtoMessage() {}

func (x *EventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPayload.ProtoReflect.Descriptor instead.
func (*EventPayload) Descriptor() ([]byte, []int) {
	return file_proto_swarm_v1_swarm_proto_rawDescGZIP(), []int{1}
}

func (x *EventPayload) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventPayload) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *EventPayload) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type TextPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	RecipientId   string                 `protobuf:"bytes,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"` // For direct messaging
	Intent        string                 `protobuf:"bytes,3,opt,name=intent,proto3" json:"intent,omitempty"`                              // "ask", "reply", "inform"
	ContextId     string                 `protobuf:"bytes,4,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`       // Thread ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextPayload) Reset() {
	*x = TextPayload{}
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextPayload) ProtoMessage() {}

func (x *TextPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextPayload.ProtoReflect.Descriptor instead.
func (*TextPayload) Descriptor() ([]byte, []int) {
	return file_proto_swarm_v1_swarm_proto_rawDescGZIP(), []int{2}
}

func (x *TextPayload) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextPayload) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *TextPayload) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *TextPayload) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

type ToolCallPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallPayload) Reset() {
	*x = ToolCallPayload{}
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallPayload) ProtoMessage() {}

func (x *ToolCallPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallPayload.ProtoReflect.Descriptor instead.
func (*ToolCallPayload) Descriptor() ([]byte, []int) {
	return file_proto_swarm_v1_swarm_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCallPayload) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCallPayload) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallPayload) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ToolResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Result        *structpb.Struct       `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	IsError       bool                   `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultPayload) Reset() {
	*x = ToolResultPayload{}
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultPayload) ProtoMessage() {}

func (x *ToolResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultPayload.ProtoReflect.Descriptor instead.
func (*ToolResultPayload) Descriptor() ([]byte, []int) {
	return file_proto_swarm_v1_swarm_proto_rawDescGZIP(), []int{4}
}

func (x *ToolResultPayload) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResultPayload) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ToolResultPayload) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ToolResultPayload) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AgentConfig struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role         string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Capabilities []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Messaging    *MessagingConfig       `protobuf:"bytes,4,opt,name=messaging,proto3" json:"messaging,omitempty"`
	// The underlying power source. Defaults to "swarm:base" if empty.
	SourceUri     string `protobuf:"bytes,5,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_proto_swarm_v1_swarm_proto_rawDescGZIP(), []int{5}
}

func (x *AgentConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentConfig) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentConfig) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentConfig) GetMessaging() *MessagingConfig {
	if x != nil {
		return x.Messaging
	}
	return nil
}

func (x *AgentConfig) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

type MessagingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inputs        []string               `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []string               `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagingConfig) Reset() {
	*x = MessagingConfig{}
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagingConfig) ProtoMessage() {}

func (x *MessagingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagingConfig.ProtoReflect.Descriptor instead.
func (*MessagingConfig) Descriptor() ([]byte, []int) {
	return file_proto_swarm_v1_swarm_proto_rawDescGZIP(), []int{6}
}

func (x *MessagingConfig) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *MessagingConfig) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// Structural Log Entry for the central nervous system (The Cortex Memory)
type LogEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                    // Precise Time
	TraceId         string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                         // Workflow Thread
	AgentId         string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                         // Actor
	TeamId          string                 `protobuf:"bytes,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`                            // Group
	SourceUri       string                 `protobuf:"bytes,5,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`                   // Capability
	Intent          string                 `protobuf:"bytes,6,opt,name=intent,proto3" json:"intent,omitempty"`                                          // "process_image", "error", "startup"
	ContextSnapshot *structpb.Struct       `protobuf:"bytes,7,opt,name=context_snapshot,json=contextSnapshot,proto3" json:"context_snapshot,omitempty"` // State at moment of event
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                                          // "SUCCESS", "FAILURE"
	ErrorMessage    string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`          // Details
	RawPayload      *anypb.Any             `protobuf:"bytes,10,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`               // Replay Data
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_swarm_v1_swarm_proto_rawDescGZIP(), []int{7}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogEntry) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *LogEntry) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *LogEntry) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *LogEntry) GetContextSnapshot() *structpb.Struct {
	if x != nil {
		return x.ContextSnapshot
	}
	return nil
}

func (x *LogEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LogEntry) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *LogEntry) GetRawPayload() *anypb.Any {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

type ApprovalRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OriginalMessage *MsgEnvelope           `protobuf:"bytes,2,opt,name=original_message,json=originalMessage,proto3" json:"original_message,omitempty"` // The suspended message
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                          // e.g. "Amount > $50"
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_proto_swarm_v1_swarm_proto_rawDescGZIP(), []int{8}
}

func (x *ApprovalRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApprovalRequest) GetOriginalMessage() *MsgEnvelope {
	if x != nil {
		return x.OriginalMessage
	}
	return nil
}

func (x *ApprovalRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ApprovalRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ApprovalSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	UserSignature string                 `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"` // "admin" or cryptographic signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalSignal) Reset() {
	*x = ApprovalSignal{}
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalSignal) ProtoMessage() {}

func (x *ApprovalSignal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_v1_swarm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalSignal.ProtoReflect.Descriptor instead.
func (*ApprovalSignal) Descriptor() ([]byte, []int) {
	return file_proto_swarm_v1_swarm_proto_rawDescGZIP(), []int{9}
}

func (x *ApprovalSignal) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApprovalSignal) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ApprovalSignal) GetUserSignature() string {
	if x != nil {
		return x.UserSignature
	}
	return ""
}

var File_proto_swarm_v1_swarm_proto protoreflect.FileDescriptor

const file_proto_swarm_v1_swarm_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/swarm/v1/swarm.proto\x12\x10mycelis.swarm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19google/protobuf/any.proto\"\xbf\x04\n" +
	"\vMsgEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12&\n" +
	"\x0fsource_agent_id\x18\x03 \x01(\tR\rsourceAgentId\x121\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1d.mycelis.swarm.v1.MessageTypeR\x04type\x126\n" +
	"\x05event\x18\x05 \x01(\v2\x1e.mycelis.swarm.v1.EventPayloadH\x00R\x05event\x123\n" +
	"\x04text\x18\x06 \x01(\v2\x1d.mycelis.swarm.v1.TextPayloadH\x00R\x04text\x12@\n" +
	"\ttool_call\x18\a \x01(\v2!.mycelis.swarm.v1.ToolCallPayloadH\x00R\btoolCall\x12F\n" +
	"\vtool_result\x18\b \x01(\v2#.mycelis.swarm.v1.ToolResultPayloadH\x00R\n" +
	"toolResult\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\v \x01(\tR\x06spanId\x12\x17\n" +
	"\ateam_id\x18\x0e \x01(\tR\x06teamId\x12<\n" +
	"\rswarm_context\x18\x0f \x01(\v2\x17.google.protobuf.StructR\fswarmContextB\t\n" +
	"\apayload\"w\n" +
	"\fEventPayload\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\"\x81\x01\n" +
	"\vTextPayload\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\tR\vrecipientId\x12\x16\n" +
	"\x06intent\x18\x03 \x01(\tR\x06intent\x12\x1d\n" +
	"\n" +
	"context_id\x18\x04 \x01(\tR\tcontextId\"~\n" +
	"\x0fToolCallPayload\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x125\n" +
	"\targuments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\targuments\"\x9d\x01\n" +
	"\x11ToolResultPayload\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xb9\x01\n" +
	"\vAgentConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12?\n" +
	"\tmessaging\x18\x04 \x01(\v2!.mycelis.swarm.v1.MessagingConfigR\tmessaging\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x05 \x01(\tR\tsourceUri\"C\n" +
	"\x0fMessagingConfig\x12\x16\n" +
	"\x06inputs\x18\x01 \x03(\tR\x06inputs\x12\x18\n" +
	"\aoutputs\x18\x02 \x03(\tR\aoutputs\"\x82\x03\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x17\n" +
	"\ateam_id\x18\x04 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x05 \x01(\tR\tsourceUri\x12\x16\n" +
	"\x06intent\x18\x06 \x01(\tR\x06intent\x12B\n" +
	"\x10context_snapshot\x18\a \x01(\v2\x17.google.protobuf.StructR\x0fcontextSnapshot\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x125\n" +
	"\vraw_payload\x18\n" +
	" \x01(\v2\x14.google.protobuf.AnyR\n" +
	"rawPayload\"\xcd\x01\n" +
	"\x0fApprovalRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12H\n" +
	"\x10original_message\x18\x02 \x01(\v2\x1d.mycelis.swarm.v1.MsgEnvelopeR\x0foriginalMessage\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"r\n" +
	"\x0eApprovalSignal\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12%\n" +
	"\x0euser_signature\x18\x03 \x01(\tR\ruserSignature*\xad\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MESSAGE_TYPE_EVENT\x10\x01\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x02\x12\x17\n" +
	"\x13MESSAGE_TYPE_BINARY\x10\x03\x12\x1a\n" +
	"\x16MESSAGE_TYPE_TOOL_CALL\x10\x04\x12\x1c\n" +
	"\x18MESSAGE_TYPE_TOOL_RESULT\x10\x05B&Z$github.com/mycelis/core/pkg/pb/swarmb\x06proto3"

var (
	file_proto_swarm_v1_swarm_proto_rawDescOnce sync.Once
	file_proto_swarm_v1_swarm_proto_rawDescData []byte
)

func file_proto_swarm_v1_swarm_proto_rawDescGZIP() []byte {
	file_proto_swarm_v1_swarm_proto_rawDescOnce.Do(func() {
		file_proto_swarm_v1_swarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_swarm_v1_swarm_proto_rawDesc), len(file_proto_swarm_v1_swarm_proto_rawDesc)))
	})
	return file_proto_swarm_v1_swarm_proto_rawDescData
}

var file_proto_swarm_v1_swarm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_swarm_v1_swarm_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_swarm_v1_swarm_proto_goTypes = []any{
	(MessageType)(0),              // 0: mycelis.swarm.v1.MessageType
	(*MsgEnvelope)(nil),           // 1: mycelis.swarm.v1.MsgEnvelope
	(*EventPayload)(nil),          // 2: mycelis.swarm.v1.EventPayload
	(*TextPayload)(nil),           // 3: mycelis.swarm.v1.TextPayload
	(*ToolCallPayload)(nil),       // 4: mycelis.swarm.v1.ToolCallPayload
	(*ToolResultPayload)(nil),     // 5: mycelis.swarm.v1.ToolResultPayload
	(*AgentConfig)(nil),           // 6: mycelis.swarm.v1.AgentConfig
	(*MessagingConfig)(nil),       // 7: mycelis.swarm.v1.MessagingConfig
	(*LogEntry)(nil),              // 8: mycelis.swarm.v1.LogEntry
	(*ApprovalRequest)(nil),       // 9: mycelis.swarm.v1.ApprovalRequest
	(*ApprovalSignal)(nil),        // 10: mycelis.swarm.v1.ApprovalSignal
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 12: google.protobuf.Struct
	(*anypb.Any)(nil),             // 13: google.protobuf.Any
}
var file_proto_swarm_v1_swarm_proto_depIdxs = []int32{
	11, // 0: mycelis.swarm.v1.MsgEnvelope.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: mycelis.swarm.v1.MsgEnvelope.type:type_name -> mycelis.swarm.v1.MessageType
	2,  // 2: mycelis.swarm.v1.MsgEnvelope.event:type_name -> mycelis.swarm.v1.EventPayload
	3,  // 3: mycelis.swarm.v1.MsgEnvelope.text:type_name -> mycelis.swarm.v1.TextPayload
	4,  // 4: mycelis.swarm.v1.MsgEnvelope.tool_call:type_name -> mycelis.swarm.v1.ToolCallPayload
	5,  // 5: mycelis.swarm.v1.MsgEnvelope.tool_result:type_name -> mycelis.swarm.v1.ToolResultPayload
	12, // 6: mycelis.swarm.v1.MsgEnvelope.swarm_context:type_name -> google.protobuf.Struct
	12, // 7: mycelis.swarm.v1.EventPayload.data:type_name -> google.protobuf.Struct
	12, // 8: mycelis.swarm.v1.ToolCallPayload.arguments:type_name -> google.protobuf.Struct
	12, // 9: mycelis.swarm.v1.ToolResultPayload.result:type_name -> google.protobuf.Struct
	7,  // 10: mycelis.swarm.v1.AgentConfig.messaging:type_name -> mycelis.swarm.v1.MessagingConfig
	11, // 11: mycelis.swarm.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	12, // 12: mycelis.swarm.v1.LogEntry.context_snapshot:type_name -> google.protobuf.Struct
	13, // 13: mycelis.swarm.v1.LogEntry.raw_payload:type_name -> google.protobuf.Any
	1,  // 14: mycelis.swarm.v1.ApprovalRequest.original_message:type_name -> mycelis.swarm.v1.MsgEnvelope
	11, // 15: mycelis.swarm.v1.ApprovalRequest.expires_at:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_swarm_v1_swarm_proto_init() }
func file_proto_swarm_v1_swarm_proto_init() {
	if File_proto_swarm_v1_swarm_proto != nil {
		return
	}
	file_proto_swarm_v1_swarm_proto_msgTypes[0].OneofWrappers = []any{
		(*MsgEnvelope_Event)(nil),
		(*MsgEnvelope_Text)(nil),
		(*MsgEnvelope_ToolCall)(nil),
		(*MsgEnvelope_ToolResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_swarm_v1_swarm_proto_rawDesc), len(file_proto_swarm_v1_swarm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_swarm_v1_swarm_proto_goTypes,
		DependencyIndexes: file_proto_swarm_v1_swarm_proto_depIdxs,
		EnumInfos:         file_proto_swarm_v1_swarm_proto_enumTypes,
		MessageInfos:      file_proto_swarm_v1_swarm_proto_msgTypes,
	}.Build()
	File_proto_swarm_v1_swarm_proto = out.File
	file_proto_swarm_v1_swarm_proto_goTypes = nil
	file_proto_swarm_v1_swarm_proto_depIdxs = nil
}
