# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: envelope.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65nvelope.proto\x12\x04scip\"\x8d\x02\n\x0eSignalEnvelope\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x11\n\tsender_id\x18\x03 \x01(\t\x12\x11\n\ttarget_id\x18\x04 \x01(\t\x12\x0e\n\x06intent\x18\x05 \x01(\t\x12\x11\n\tsignature\x18\x06 \x01(\t\x12,\n\x04meta\x18\x07 \x03(\x0b\x32\x1e.scip.SignalEnvelope.MetaEntry\x12!\n\tdata_type\x18\x08 \x01(\x0e\x32\x0e.scip.DataType\x12\x0f\n\x07payload\x18\t \x01(\x0c\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*M\n\x08\x44\x61taType\x12\r\n\tTEXT_UTF8\x10\x00\x12\x10\n\x0cTENSOR_FLOAT\x10\x01\x12\x10\n\x0cIMAGE_BINARY\x10\x02\x12\x0e\n\nSTATE_DIFF\x10\x03\x42\"Z github.com/mycelis/core/pkg/scipb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/mycelis/core/pkg/scip'
  _globals['_SIGNALENVELOPE_METAENTRY']._loaded_options = None
  _globals['_SIGNALENVELOPE_METAENTRY']._serialized_options = b'8\001'
  _globals['_DATATYPE']._serialized_start=296
  _globals['_DATATYPE']._serialized_end=373
  _globals['_SIGNALENVELOPE']._serialized_start=25
  _globals['_SIGNALENVELOPE']._serialized_end=294
  _globals['_SIGNALENVELOPE_METAENTRY']._serialized_start=251
  _globals['_SIGNALENVELOPE_METAENTRY']._serialized_end=294
# @@protoc_insertion_point(module_scope)
