-- Migration 002: V6 Core Schema (Identity & Provisioning)

-- 1. Users (Tier 0 Authority)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'operator', -- admin, operator, observer
    settings JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Teams (Tenancy)
CREATE TABLE IF NOT EXISTS teams (
    id UUID PRIMARY KEY,
    owner_id UUID REFERENCES users(id),
    name TEXT NOT NULL,
    role TEXT DEFAULT 'admin', -- Contextual role
    settings JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Service Manifests (The Forge Output)
CREATE TABLE IF NOT EXISTS service_manifests (
    id UUID PRIMARY KEY,
    team_id UUID REFERENCES teams(id),
    name TEXT NOT NULL,
    manifest JSONB NOT NULL, -- The immutable JSON config generated by The Architect
    status TEXT DEFAULT 'draft', -- draft, active, paused, error
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
