-- Migration 008: The Context Engine (Semantic Memory & SitReps)
-- 1. Context Vectors (Semantic Search)
-- Optimized for RAG (Retrieval Augmented Generation) by the Cognitive Engine.
-- We use 768 dimensions (STANDARD for modern embeddings like nomic-embed-text/v1.5 or all-minilm).
CREATE TABLE IF NOT EXISTS context_vectors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content TEXT NOT NULL,
    -- The text chunk
    metadata JSONB DEFAULT '{}',
    -- Source: {file: "task.md", type: "doc"}
    embedding vector(768),
    -- The semantic vector
    created_at TIMESTAMPTZ DEFAULT NOW()
);
-- Index for Fast ANN Search (IVFFlat)
-- Note: Requires some data to be effective but good to define template.
-- CREATE INDEX ON context_vectors USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
-- 2. Situation Reports (SitReps)
-- Generated by the Archivist (LLM) summarizing time-series logs.
CREATE TABLE IF NOT EXISTS sitreps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id UUID REFERENCES teams(id),
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    -- When the report was generated
    time_window_start TIMESTAMPTZ NOT NULL,
    time_window_end TIMESTAMPTZ NOT NULL,
    summary TEXT NOT NULL,
    -- High-level narrative
    key_events JSONB DEFAULT '[]',
    -- Structured extraction of critical events
    strategies TEXT,
    -- "Continue monitoring", "Deploy fix"
    status TEXT DEFAULT 'active' -- active, archived
);
-- 3. Short Term Memory (Working Context)
-- Fast Key-Value store for agent collaboration context (e.g. "What are we working on?")
CREATE TABLE IF NOT EXISTS working_memory (
    key TEXT PRIMARY KEY,
    -- "team:core:current_objective"
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ -- Optional TTL
);