# Build Stage
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Copy dependency files
# Just go.mod for now as we haven't run tidy yet
COPY core/go.mod ./

# Download modules
RUN go mod download

# Copy source
COPY core/ ./

# Build
# CGO_ENABLED=0 for static binary
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/server ./cmd/server

# Run Stage
FROM gcr.io/distroless/static-debian12

COPY --from=builder /bin/server /server

ENTRYPOINT ["/server"]
