{{- if and (or .Values.coreAuth.apiKey .Values.coreAuth.existingSecret) (not .Values.coreAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mycelis-core.coreAuthSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  mycelis-api-key: {{ .Values.coreAuth.apiKey | b64enc | quote }}
{{- end }}
