{{- if .Values.frameworkWorker.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-framework-runs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: framework-runs
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
{{- end }}
