import type { CortexState } from '@/store/cortexStoreState';
import { deriveMissionChatState } from '@/store/cortexStoreChatWorkflow';
import { loadPersistedChat } from '@/store/cortexStoreUtils';

const initialMissionChat = loadPersistedChat(null);
const initialMissionChatState = deriveMissionChatState(initialMissionChat);

// Keep the default store state isolated from action logic so product behavior
// slices are easier to review and reuse without re-scanning the whole store.
export const initialCortexState: Omit<
    CortexState,
    | 'onNodesChange'
    | 'onEdgesChange'
    | 'submitIntent'
    | 'instantiateMission'
    | 'fetchMissions'
    | 'initializeStream'
    | 'disconnectStream'
    | 'enterSquadRoom'
    | 'exitSquadRoom'
    | 'selectArtifact'
    | 'approveArtifact'
    | 'rejectArtifact'
    | 'setTrustThreshold'
    | 'fetchTrustThreshold'
    | 'toggleBlueprintDrawer'
    | 'toggleToolsPalette'
    | 'setStatusDrawerOpen'
    | 'saveBlueprint'
    | 'loadBlueprint'
    | 'fetchSensors'
    | 'toggleSensorGroup'
    | 'fetchProposals'
    | 'approveProposal'
    | 'rejectProposal'
    | 'fetchCatalogue'
    | 'createCatalogueAgent'
    | 'updateCatalogueAgent'
    | 'deleteCatalogueAgent'
    | 'selectCatalogueAgent'
    | 'fetchArtifacts'
    | 'getArtifactDetail'
    | 'updateArtifactStatus'
    | 'fetchMCPServers'
    | 'deleteMCPServer'
    | 'fetchMCPTools'
    | 'fetchMCPLibrary'
    | 'installFromLibrary'
    | 'sendMissionChat'
    | 'clearMissionChat'
    | 'setMissionChatScope'
    | 'fetchUserSettings'
    | 'updateAssistantName'
    | 'updateTheme'
    | 'setCouncilTarget'
    | 'fetchCouncilMembers'
    | 'broadcastToSwarm'
    | 'confirmProposal'
    | 'cancelProposal'
    | 'fetchRunTimeline'
    | 'fetchRecentRuns'
    | 'fetchTeamDetails'
    | 'fetchPolicy'
    | 'updatePolicy'
    | 'fetchPendingApprovals'
    | 'resolveApproval'
    | 'fetchAuditLog'
    | 'fetchCognitiveStatus'
    | 'fetchServicesStatus'
    | 'fetchTeamsDetail'
    | 'selectTeam'
    | 'setTeamsFilter'
    | 'selectAgentNode'
    | 'updateAgentInDraft'
    | 'deleteAgentFromDraft'
    | 'discardDraft'
    | 'updateAgentInMission'
    | 'deleteAgentFromMission'
    | 'deleteMission'
    | 'selectSignalDetail'
    | 'setInspectedMessage'
    | 'fetchMissionProfiles'
    | 'createMissionProfile'
    | 'updateMissionProfile'
    | 'deleteMissionProfile'
    | 'activateMissionProfile'
    | 'fetchContextSnapshots'
    | 'createContextSnapshot'
    | 'fetchTriggerRules'
    | 'createTriggerRule'
    | 'updateTriggerRule'
    | 'deleteTriggerRule'
    | 'toggleTriggerRule'
    | 'fetchRunConversation'
    | 'interjectInRun'
    | 'toggleAdvancedMode'
> = {
    chatHistory: [],
    nodes: [],
    edges: [],
    isDrafting: false,
    isCommitting: false,
    error: null,
    blueprint: null,
    missionStatus: 'idle',
    activeMissionId: null,
    streamLogs: [],
    isStreamConnected: false,
    streamConnectionState: 'idle',
    activeSquadRoomId: null,
    pendingArtifacts: [],
    selectedArtifact: null,
    missions: [],
    isFetchingMissions: false,
    trustThreshold: 0.7,
    isSyncingThreshold: false,
    savedBlueprints: [],
    isBlueprintDrawerOpen: false,
    advancedMode:
        typeof window !== 'undefined'
        && typeof localStorage !== 'undefined'
        && typeof localStorage.getItem === 'function'
        ? localStorage.getItem('mycelis-advanced-mode') === 'true'
        : false,
    isToolsPaletteOpen: false,
    sensorFeeds: [],
    isFetchingSensors: false,
    subscribedSensorGroups: [],
    teamProposals: [],
    isFetchingProposals: false,
    catalogueAgents: [],
    isFetchingCatalogue: false,
    selectedCatalogueAgent: null,
    artifacts: [],
    isFetchingArtifacts: false,
    selectedArtifactDetail: null,
    mcpServers: [],
    isFetchingMCPServers: false,
    mcpTools: [],
    mcpLibrary: [],
    isFetchingMCPLibrary: false,
    workspaceChatScope: null,
    missionChat: initialMissionChat,
    isMissionChatting: false,
    missionChatError: null,
    missionChatFailure: null,
    workspaceChatPrimed: false,
    assistantName: 'Soma',
    theme: 'aero-light',
    councilTarget: 'admin',
    councilMembers: [],
    isBroadcasting: false,
    lastBroadcastResult: null,
    teamRoster: [],
    isFetchingTeamRoster: false,
    policyConfig: null,
    pendingApprovals: [],
    isFetchingPolicy: false,
    isFetchingApprovals: false,
    auditLog: [],
    isFetchingAuditLog: false,
    cognitiveStatus: null,
    servicesStatus: [],
    isFetchingServicesStatus: false,
    servicesStatusUpdatedAt: null,
    teamsDetail: [],
    isFetchingTeamsDetail: false,
    selectedTeamId: null,
    isTeamDrawerOpen: false,
    teamsFilter: 'all',
    selectedAgentNodeId: null,
    isAgentEditorOpen: false,
    pendingProposal: initialMissionChatState.pendingProposal,
    activeConfirmToken: initialMissionChatState.activeConfirmToken,
    lastCommitProof: null,
    activeRunId: initialMissionChatState.activeRunId,
    runTimeline: null,
    isFetchingTimeline: false,
    recentRuns: [],
    isFetchingRuns: false,
    triggerRules: [],
    isFetchingTriggers: false,
    conversationTurns: null,
    isFetchingConversation: false,
    selectedSignalDetail: null,
    activeBrain: null,
    activeMode: initialMissionChatState.activeMode,
    activeRole: '',
    governanceMode: 'passive',
    inspectedMessage: null,
    isInspectorOpen: false,
    isStatusDrawerOpen: false,
    missionProfiles: [],
    activeProfileId: null,
    contextSnapshots: [],
};
