package swarm

func (r *InternalToolRegistry) registerExecutionAndMediaTools() {
	r.tools["publish_signal"] = &InternalTool{Name: "publish_signal", Description: "Publish a message to a NATS topic in the swarm with optional private reference mode.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"subject": map[string]any{"type": "string", "description": "NATS subject"}, "message": map[string]any{"type": "string", "description": "Message payload to publish"}, "channel_key": map[string]any{"type": "string", "description": "Optional private checkpoint channel key"}, "privacy_mode": map[string]any{"type": "string", "description": "full (default) or reference"}, "private": map[string]any{"type": "boolean", "description": "Alias for privacy_mode=reference."}, "file_path": map[string]any{"type": "string", "description": "Optional workspace file path to attach as a private file reference"}}}, Handler: r.handlePublishSignal}
	r.tools["broadcast"] = &InternalTool{Name: "broadcast", Description: "Send a message to all active teams in the swarm.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"message": map[string]any{"type": "string", "description": "The message to broadcast to all teams"}, "urgency": map[string]any{"type": "string", "description": "Optional urgency level", "enum": []string{"low", "medium", "high", "critical"}}}, "required": []string{"message"}}, Handler: r.handleBroadcast}
	r.tools["send_external_message"] = &InternalTool{Name: "send_external_message", Description: "Send a message through an external communication provider.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"provider": map[string]any{"type": "string", "description": "Provider name"}, "recipient": map[string]any{"type": "string", "description": "Recipient handle/ID/number/channel"}, "message": map[string]any{"type": "string", "description": "Message body"}, "metadata": map[string]any{"type": "object", "description": "Optional metadata map"}}, "required": []string{"provider", "message"}}, Handler: r.handleSendExternalMessage}
	r.tools["read_signals"] = &InternalTool{Name: "read_signals", Description: "Subscribe to NATS and collect messages for a brief window, or read the latest persisted checkpoint.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"subject": map[string]any{"type": "string", "description": "NATS subject or wildcard"}, "channel_key": map[string]any{"type": "string", "description": "Optional checkpoint channel key"}, "latest_only": map[string]any{"type": "boolean", "description": "Return latest checkpoint instead of live subscription"}, "duration_ms": map[string]any{"type": "integer", "description": "How long to listen in milliseconds"}, "max_msgs": map[string]any{"type": "integer", "description": "Max messages to collect"}}, "required": []string{"subject"}}, Handler: r.handleReadSignals}
	r.tools["read_file"] = &InternalTool{Name: "read_file", Description: "Read the contents of a file within the workspace sandbox.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"path": map[string]any{"type": "string", "description": "File path relative to workspace root, or absolute path within workspace"}}, "required": []string{"path"}}, Handler: r.handleReadFile}
	r.tools["write_file"] = &InternalTool{Name: "write_file", Description: "Write content to a file within the workspace sandbox.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"path": map[string]any{"type": "string", "description": "File path relative to workspace root, or absolute path within workspace"}, "content": map[string]any{"type": "string", "description": "The file content to write"}}, "required": []string{"path", "content"}}, Handler: r.handleWriteFile}
	r.tools["local_command"] = &InternalTool{Name: "local_command", Description: "Execute one local command from the allowlist without shell interpolation.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"command": map[string]any{"type": "string", "description": "Allowlisted command name"}, "args": map[string]any{"type": "array", "items": map[string]any{"type": "string"}, "description": "Command arguments"}, "timeout_ms": map[string]any{"type": "integer", "description": "Optional timeout in milliseconds"}}, "required": []string{"command"}}, Handler: r.handleLocalCommand}
	r.tools["generate_image"] = &InternalTool{Name: "generate_image", Description: "Generate an image from a text prompt using the local Diffusers media engine.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"prompt": map[string]any{"type": "string", "description": "Text description of the image to generate"}, "size": map[string]any{"type": "string", "description": "Image dimensions"}}, "required": []string{"prompt"}}, Handler: r.handleGenerateImage}
	r.tools["save_cached_image"] = &InternalTool{Name: "save_cached_image", Description: "Persist a cached generated image into the workspace saved-media folder.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"artifact_id": map[string]any{"type": "string", "description": "Optional image artifact ID"}, "folder": map[string]any{"type": "string", "description": "Optional workspace-relative folder"}, "filename": map[string]any{"type": "string", "description": "Optional target filename"}}}, Handler: r.handleSaveCachedImage}
	r.tools["store_inception_recipe"] = &InternalTool{Name: "store_inception_recipe", Description: "Store a structured inception recipe for future reuse.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"category": map[string]any{"type": "string", "description": "Recipe category"}, "title": map[string]any{"type": "string", "description": "Short descriptive title"}, "intent_pattern": map[string]any{"type": "string", "description": "Structured way to phrase this request"}, "parameters": map[string]any{"type": "object", "description": "Key parameters as name→description pairs"}, "example_prompt": map[string]any{"type": "string", "description": "A concrete example prompt"}, "outcome_shape": map[string]any{"type": "string", "description": "What the successful outcome looks like"}, "tags": map[string]any{"type": "array", "items": map[string]any{"type": "string"}, "description": "Searchable tags for filtering"}}, "required": []string{"category", "title", "intent_pattern"}}, Handler: r.handleStoreInceptionRecipe}
	r.tools["recall_inception_recipes"] = &InternalTool{Name: "recall_inception_recipes", Description: "Recall inception recipes by keyword or category.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"query": map[string]any{"type": "string", "description": "Search query"}, "category": map[string]any{"type": "string", "description": "Optional category filter"}, "limit": map[string]any{"type": "integer", "description": "Max results (default 5)"}}, "required": []string{"query"}}, Handler: r.handleRecallInceptionRecipes}
	r.tools["store_conversation_template"] = &InternalTool{Name: "store_conversation_template", Description: "Store a reusable Soma, council, team, or temporary-group conversation template without executing it.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"name": map[string]any{"type": "string", "description": "Template name"}, "scope": map[string]any{"type": "string", "enum": []string{"soma", "council", "team", "temporary_group"}}, "template_body": map[string]any{"type": "string", "description": "Prompt body with {{variable}} placeholders"}, "description": map[string]any{"type": "string"}, "variables": map[string]any{"type": "object"}, "output_contract": map[string]any{"type": "object"}, "recommended_team_shape": map[string]any{"type": "object"}, "model_routing_hint": map[string]any{"type": "object"}, "governance_tags": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}}, "required": []string{"name", "scope", "template_body"}}, Handler: r.handleStoreConversationTemplate}
	r.tools["instantiate_conversation_template"] = &InternalTool{Name: "instantiate_conversation_template", Description: "Render a registered conversation template into a non-executing ask package.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"template_id": map[string]any{"type": "string", "description": "Registered conversation template ID"}, "variables": map[string]any{"type": "object", "description": "Values for {{variable}} placeholders"}}, "required": []string{"template_id"}}, Handler: r.handleInstantiateConversationTemplate}
}
