package swarm

func (r *InternalToolRegistry) registerExchangeAndPlanningTools() {
	r.tools["list_exchange_channels"] = &InternalTool{Name: "list_exchange_channels", Description: "List the managed exchange channels available for governed work, review, learning, and tool output.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{}}, Handler: r.handleListExchangeChannels}
	r.tools["list_exchange_threads"] = &InternalTool{Name: "list_exchange_threads", Description: "List managed exchange threads for a channel, optionally filtering by status.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"channel": map[string]any{"type": "string", "description": "Optional channel name filter"}, "status": map[string]any{"type": "string", "description": "Optional thread status filter"}, "limit": map[string]any{"type": "integer", "description": "Optional limit"}}}, Handler: r.handleListExchangeThreads}
	r.tools["search_exchange_items"] = &InternalTool{Name: "search_exchange_items", Description: "Semantic search across managed exchange items to find related prior outputs and continuity context.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"query": map[string]any{"type": "string", "description": "Semantic search query"}, "limit": map[string]any{"type": "integer", "description": "Optional result limit"}}, "required": []string{"query"}}, Handler: r.handleSearchExchangeItems}
	r.tools["create_exchange_thread"] = &InternalTool{Name: "create_exchange_thread", Description: "Create a managed exchange thread for planning, work, review, escalation, or learning.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"channel": map[string]any{"type": "string", "description": "Registered channel name"}, "title": map[string]any{"type": "string", "description": "Thread title"}, "thread_type": map[string]any{"type": "string", "description": "planning_thread, work_thread, review_thread, escalation_thread, or learning_thread"}, "participants": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "continuity_key": map[string]any{"type": "string", "description": "Optional continuity key"}, "created_by": map[string]any{"type": "string", "description": "Optional creator role"}}, "required": []string{"channel", "title"}}, Handler: r.handleCreateExchangeThread}
	r.tools["publish_exchange_item"] = &InternalTool{Name: "publish_exchange_item", Description: "Publish a structured managed exchange item into a governed channel or thread. Use schema_id=LearningCandidate on organization.learning.candidates for classified learning/reflection candidates before any memory promotion.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"channel": map[string]any{"type": "string", "description": "Registered channel name"}, "schema_id": map[string]any{"type": "string", "description": "Registered schema ID"}, "payload": map[string]any{"type": "object", "description": "Structured exchange payload; LearningCandidate requires summary, status, classification, memory_layer, confidence, review_required, tags, continuity_key, and created_at"}, "summary": map[string]any{"type": "string", "description": "Optional summary override"}, "addressed_to": map[string]any{"type": "string", "description": "Optional target role or team"}, "thread_id": map[string]any{"type": "string", "description": "Optional thread UUID"}, "visibility": map[string]any{"type": "string", "description": "Optional visibility override"}, "sensitivity_class": map[string]any{"type": "string", "description": "Optional sensitivity override"}, "source_role": map[string]any{"type": "string", "description": "Optional source role"}, "source_team": map[string]any{"type": "string", "description": "Optional source team"}, "target_role": map[string]any{"type": "string", "description": "Optional target role"}, "target_team": map[string]any{"type": "string", "description": "Optional target team"}, "allowed_consumers": map[string]any{"type": "array", "items": map[string]any{"type": "string"}, "description": "Optional allowed downstream consumers"}, "capability_id": map[string]any{"type": "string", "description": "Optional capability identifier"}, "trust_class": map[string]any{"type": "string", "description": "Optional trust class"}, "review_required": map[string]any{"type": "boolean", "description": "Whether review is required before relying on or promoting the item"}, "created_by": map[string]any{"type": "string", "description": "Optional creator role"}}, "required": []string{"channel", "schema_id", "payload"}}, Handler: r.handlePublishExchangeItem}
	r.tools["generate_blueprint"] = &InternalTool{Name: "generate_blueprint", Description: "Invoke the Meta-Architect to generate a MissionBlueprint from natural language intent.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"intent": map[string]any{"type": "string", "description": "The natural language intent to decompose"}}, "required": []string{"intent"}}, Handler: r.handleGenerateBlueprint}
	r.tools["research_for_blueprint"] = &InternalTool{Name: "research_for_blueprint", Description: "Conduct multi-source research before generating a mission blueprint. Queries past missions, catalogue, tools, and recipes.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"intent": map[string]any{"type": "string", "description": "The user's natural language intent to research"}}, "required": []string{"intent"}}, Handler: r.handleResearchForBlueprint}
	r.tools["list_catalogue"] = &InternalTool{Name: "list_catalogue", Description: "Returns agent catalogue templates (reusable agent blueprints).", InputSchema: map[string]any{"type": "object", "properties": map[string]any{}}, Handler: r.handleListCatalogue}
}
