package swarm

func (r *InternalToolRegistry) registerMemoryAndArtifactTools() {
	r.tools["search_memory"] = &InternalTool{Name: "search_memory", Description: "Semantic search over durable memory with optional team, agent, visibility, and type scope.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"query": map[string]any{"type": "string", "description": "The search query text"}, "limit": map[string]any{"type": "integer", "description": "Max results (default 5)"}, "team_id": map[string]any{"type": "string", "description": "Optional team scope override"}, "agent_id": map[string]any{"type": "string", "description": "Optional private-agent scope override"}, "type": map[string]any{"type": "string", "description": "Optional durable memory type filter"}, "types": map[string]any{"type": "array", "items": map[string]any{"type": "string"}, "description": "Optional durable memory type filters"}, "visibility": map[string]any{"type": "string", "description": "Optional visibility override: private, team, global"}}, "required": []string{"query"}}, Handler: r.handleSearchMemory}
	r.tools["remember"] = &InternalTool{Name: "remember", Description: "Store a learned fact, user preference, or goal into persistent memory.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"category": map[string]any{"type": "string", "description": "Category: user_preference, goal, fact, decision, lesson_learned"}, "content": map[string]any{"type": "string", "description": "The information to remember"}, "context": map[string]any{"type": "string", "description": "Optional context about when/why this was learned"}, "team_id": map[string]any{"type": "string", "description": "Optional team ownership override"}, "agent_id": map[string]any{"type": "string", "description": "Optional private owner override"}, "visibility": map[string]any{"type": "string", "description": "Optional visibility override: private, team, global"}}, "required": []string{"category", "content"}}, Handler: r.handleRemember}
	r.tools["recall"] = &InternalTool{Name: "recall", Description: "Recall stored memories by semantic similarity. Searches both vector embeddings and structured records.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"query": map[string]any{"type": "string", "description": "What to recall — natural language query"}, "category": map[string]any{"type": "string", "description": "Optional filter"}, "limit": map[string]any{"type": "integer", "description": "Max results (default 5)"}, "team_id": map[string]any{"type": "string", "description": "Optional team scope override"}, "agent_id": map[string]any{"type": "string", "description": "Optional private-agent scope override"}, "visibility": map[string]any{"type": "string", "description": "Optional visibility override: private, team, global"}}, "required": []string{"query"}}, Handler: r.handleRecall}
	r.tools["temp_memory_write"] = &InternalTool{Name: "temp_memory_write", Description: "Persist a temporary working-memory checkpoint (restart-safe) for lead-agent continuity.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"channel": map[string]any{"type": "string", "description": "Channel key"}, "content": map[string]any{"type": "string", "description": "Checkpoint content"}, "owner_agent_id": map[string]any{"type": "string", "description": "Optional owner identity"}, "ttl_minutes": map[string]any{"type": "integer", "description": "Optional expiration in minutes"}, "metadata": map[string]any{"type": "object", "description": "Optional structured metadata"}}, "required": []string{"channel", "content"}}, Handler: r.handleTempMemoryWrite}
	r.tools["temp_memory_read"] = &InternalTool{Name: "temp_memory_read", Description: "Read recent temporary working-memory checkpoints for a channel.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"channel": map[string]any{"type": "string", "description": "Channel key"}, "limit": map[string]any{"type": "integer", "description": "Max entries (default 10)"}}, "required": []string{"channel"}}, Handler: r.handleTempMemoryRead}
	r.tools["temp_memory_clear"] = &InternalTool{Name: "temp_memory_clear", Description: "Clear a temporary working-memory channel.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"channel": map[string]any{"type": "string", "description": "Channel key"}}, "required": []string{"channel"}}, Handler: r.handleTempMemoryClear}
	r.tools["summarize_conversation"] = &InternalTool{Name: "summarize_conversation", Description: "Summarize recent conversation into deliberate persistent memory.", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"messages": map[string]any{"type": "string", "description": "The conversation text to summarize"}, "team_id": map[string]any{"type": "string", "description": "Optional team ownership override"}, "agent_id": map[string]any{"type": "string", "description": "Optional private owner override"}, "visibility": map[string]any{"type": "string", "description": "Optional visibility override: private, team, global"}}, "required": []string{"messages"}}, Handler: r.handleSummarizeConversation}
	r.tools["store_artifact"] = &InternalTool{Name: "store_artifact", Description: `Persist an agent output as a typed artifact. For type="chart", content MUST be a JSON chart spec with version, chart_type, data, x, and y fields.`, InputSchema: map[string]any{"type": "object", "properties": map[string]any{"type": map[string]any{"type": "string", "description": "Artifact type: code, document, image, data, file, chart"}, "title": map[string]any{"type": "string", "description": "Human-readable title"}, "content": map[string]any{"type": "string", "description": "The artifact content"}, "metadata": map[string]any{"type": "object", "description": "Optional key-value metadata"}}, "required": []string{"type", "title", "content"}}, Handler: r.handleStoreArtifact}
}
