// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/envelope.proto

package scip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_TEXT_UTF8    DataType = 0 // Standard Chat / JSON
	DataType_TENSOR_FLOAT DataType = 1 // Sensor Arrays (IMU, Audio embeddings)
	DataType_IMAGE_BINARY DataType = 2 // Raw JPG/PNG bytes
	DataType_STATE_DIFF   DataType = 3 // CRDT / Delta updates
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "TEXT_UTF8",
		1: "TENSOR_FLOAT",
		2: "IMAGE_BINARY",
		3: "STATE_DIFF",
	}
	DataType_value = map[string]int32{
		"TEXT_UTF8":    0,
		"TENSOR_FLOAT": 1,
		"IMAGE_BINARY": 2,
		"STATE_DIFF":   3,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_envelope_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_proto_envelope_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_envelope_proto_rawDescGZIP(), []int{0}
}

type SignalEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1. HEADER (Context & Routing)
	TraceId   string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`    // UUID for tracking flows across the swarm
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // UTC Unix Nanoseconds
	SenderId  string `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // e.g., "agent:camera-01" or "user:tier-0"
	TargetId  string `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // e.g., "agent:vision-model"
	Intent    string `protobuf:"bytes,5,opt,name=intent,proto3" json:"intent,omitempty"`                     // e.g., "ingest.frame" or "chat.query"
	// 2. SECURITY (Hardened Hull)
	Signature string            `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                                                                 // HMAC-SHA256 of payload (Anti-Tamper)
	Meta      map[string]string `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Lightweight context (e.g., "priority": "high")
	// 3. THE PAYLOAD (Polymorphic Data)
	DataType      DataType `protobuf:"varint,8,opt,name=data_type,json=dataType,proto3,enum=scip.DataType" json:"data_type,omitempty"` // Enum: TEXT, TENSOR, IMAGE_REF, BINARY
	Payload       []byte   `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`                                       // The actual data (Compressed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalEnvelope) Reset() {
	*x = SignalEnvelope{}
	mi := &file_proto_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalEnvelope) ProtoMessage() {}

func (x *SignalEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalEnvelope.ProtoReflect.Descriptor instead.
func (*SignalEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *SignalEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SignalEnvelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SignalEnvelope) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SignalEnvelope) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *SignalEnvelope) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *SignalEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignalEnvelope) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SignalEnvelope) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_TEXT_UTF8
}

func (x *SignalEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_envelope_proto protoreflect.FileDescriptor

const file_proto_envelope_proto_rawDesc = "" +
	"\n" +
	"\x14proto/envelope.proto\x12\x04scip\"\xed\x02\n" +
	"\x0eSignalEnvelope\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x12\x16\n" +
	"\x06intent\x18\x05 \x01(\tR\x06intent\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x122\n" +
	"\x04meta\x18\a \x03(\v2\x1e.scip.SignalEnvelope.MetaEntryR\x04meta\x12+\n" +
	"\tdata_type\x18\b \x01(\x0e2\x0e.scip.DataTypeR\bdataType\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*M\n" +
	"\bDataType\x12\r\n" +
	"\tTEXT_UTF8\x10\x00\x12\x10\n" +
	"\fTENSOR_FLOAT\x10\x01\x12\x10\n" +
	"\fIMAGE_BINARY\x10\x02\x12\x0e\n" +
	"\n" +
	"STATE_DIFF\x10\x03B\"Z github.com/mycelis/core/pkg/scipb\x06proto3"

var (
	file_proto_envelope_proto_rawDescOnce sync.Once
	file_proto_envelope_proto_rawDescData []byte
)

func file_proto_envelope_proto_rawDescGZIP() []byte {
	file_proto_envelope_proto_rawDescOnce.Do(func() {
		file_proto_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_envelope_proto_rawDesc), len(file_proto_envelope_proto_rawDesc)))
	})
	return file_proto_envelope_proto_rawDescData
}

var file_proto_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_envelope_proto_goTypes = []any{
	(DataType)(0),          // 0: scip.DataType
	(*SignalEnvelope)(nil), // 1: scip.SignalEnvelope
	nil,                    // 2: scip.SignalEnvelope.MetaEntry
}
var file_proto_envelope_proto_depIdxs = []int32{
	2, // 0: scip.SignalEnvelope.meta:type_name -> scip.SignalEnvelope.MetaEntry
	0, // 1: scip.SignalEnvelope.data_type:type_name -> scip.DataType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_envelope_proto_init() }
func file_proto_envelope_proto_init() {
	if File_proto_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_envelope_proto_rawDesc), len(file_proto_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_envelope_proto_goTypes,
		DependencyIndexes: file_proto_envelope_proto_depIdxs,
		EnumInfos:         file_proto_envelope_proto_enumTypes,
		MessageInfos:      file_proto_envelope_proto_msgTypes,
	}.Build()
	File_proto_envelope_proto = out.File
	file_proto_envelope_proto_goTypes = nil
	file_proto_envelope_proto_depIdxs = nil
}
