"""Canonical runtime schema compatibility checks and targeted repair mapping."""

SCHEMA_COMPATIBILITY_CHECKS = (
    ("nodes.type column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'nodes' AND column_name = 'type';"),
    ("nodes.specs column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'nodes' AND column_name = 'specs';"),
    ("intent_proofs table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'intent_proofs';"),
    ("confirm_tokens table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'confirm_tokens';"),
    ("conversation_turns table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'conversation_turns';"),
    ("collaboration_groups table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'collaboration_groups';"),
    ("collaboration_groups workspace_folder column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'collaboration_groups' AND column_name = 'workspace_folder';"),
    ("capability_manifests table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'capability_manifests';"),
    ("capability_manifests health column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'capability_manifests' AND column_name = 'health';"),
    ("execution_contracts table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'execution_contracts';"),
    ("proof_artifacts table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'proof_artifacts';"),
    ("team_work_items table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'team_work_items';"),
    ("team_work_items work_intent column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'team_work_items' AND column_name = 'work_intent' AND data_type = 'jsonb';"),
    ("team_work_items execution_mode column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'team_work_items' AND column_name = 'execution_mode' AND data_type = 'text';"),
    ("team_work_items recovery_deadline_at column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'team_work_items' AND column_name = 'recovery_deadline_at' AND data_type = 'timestamp with time zone';"),
    ("team_interactions table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'team_interactions';"),
    ("team_status_events table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'team_status_events';"),
    ("team_status_events work_intent column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'team_status_events' AND column_name = 'work_intent' AND data_type = 'jsonb';"),
    ("team_status_events execution_mode column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'team_status_events' AND column_name = 'execution_mode' AND data_type = 'text';"),
    ("outcome_projects table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'outcome_projects';"),
    ("outcome_projects run_id text column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'outcome_projects' AND column_name = 'run_id' AND data_type = 'text';"),
    ("outcome_projects intent_proof_id text column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'outcome_projects' AND column_name = 'intent_proof_id' AND data_type = 'text';"),
    ("team_registry_entries table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'team_registry_entries';"),
    ("trigger_rules schedule columns", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'trigger_rules' AND column_name = 'trigger_kind';"),
    ("search_sources table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'search_sources';"),
    ("input_sources table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'input_sources';"),
    ("execution_dispatch_outbox table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'execution_dispatch_outbox';"),
    ("operator_sse_events table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'operator_sse_events';"),
    ("team_signal_receipts table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'team_signal_receipts';"),
    ("agent_catalogue profile_key column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'agent_catalogue' AND column_name = 'profile_key';"),
    ("qa_fixture_scopes table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'qa_fixture_scopes';"),
    ("qa_fixture_resources table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'qa_fixture_resources';"),
    ("qa_fixture resource ownership index", "SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'uq_qa_fixture_resource_claim';"),
    ("purged QA fixture claims released", "SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM qa_fixture_resources r JOIN qa_fixture_scopes s ON s.id=r.scope_id WHERE s.status='purged');"),
    ("config_documents table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'config_documents';"),
    ("config_document_activations table", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'config_document_activations' AND column_name = 'kind';"),
    ("config_document_activation_history table", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'config_document_activation_history' AND column_name = 'kind';"),
    ("config_document fixture ownership", "SELECT 1 FROM pg_constraint WHERE conname = 'chk_qa_fixture_resource_kind' AND pg_get_constraintdef(oid) LIKE '%config_document%';"),
)

TARGETED_SCHEMA_MIGRATIONS = {
    "agent_catalogue profile_key column": "056_agent_profile_library.up.sql",
    "team_work_items recovery_deadline_at column": "057_team_work_recovery_deadline.up.sql",
    "qa_fixture_scopes table": "058_qa_fixture_ownership.up.sql",
    "qa_fixture_resources table": "058_qa_fixture_ownership.up.sql",
    "qa_fixture resource ownership index": "059_qa_fixture_ownership_hardening.up.sql",
    "purged QA fixture claims released": "060_release_purged_qa_fixture_claims.up.sql",
    "config_documents table": "061_config_documents.up.sql",
    "config_document_activations table": "061_config_documents.up.sql",
    "config_document_activation_history table": "061_config_documents.up.sql",
    "config_document fixture ownership": "062_qa_fixture_config_documents.up.sql",
}
