"""Canonical current-schema installer and compatibility contract."""

CANONICAL_SCHEMA_NAME = "001_current_schema.sql"
PUBLIC_SCHEMA_NONEMPTY_SQL = (
    "SELECT 1 WHERE EXISTS (SELECT 1 FROM information_schema.tables "
    "WHERE table_schema = 'public' AND table_type = 'BASE TABLE');"
)

SCHEMA_COMPATIBILITY_CHECKS = (
    ("pgvector extension", "SELECT 1 FROM pg_extension WHERE extname = 'vector';"),
    ("semantic context vectors", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'context_vectors';"),
    ("durable agent memory", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'agent_memories';"),
    ("retained artifacts", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'artifacts';"),
    ("temporary continuity", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'temp_memory_channels';"),
    ("managed exchange channels", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'exchange_channels';"),
    ("managed exchange items", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'exchange_items';"),
    ("conversation templates", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'conversation_templates';"),
    ("nodes.type column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'nodes' AND column_name = 'type';"),
    ("nodes.specs column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'nodes' AND column_name = 'specs';"),
    ("intent_proofs table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'intent_proofs';"),
    ("confirm_tokens table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'confirm_tokens';"),
    ("conversation_turns table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'conversation_turns';"),
    ("collaboration_groups table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'collaboration_groups';"),
    ("collaboration_groups workspace_folder column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'collaboration_groups' AND column_name = 'workspace_folder';"),
    ("capability_manifests table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'capability_manifests';"),
    ("capability_manifests health column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'capability_manifests' AND column_name = 'health';"),
    ("execution_contracts table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'execution_contracts';"),
    ("proof_artifacts table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'proof_artifacts';"),
    ("team_work_items table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'team_work_items';"),
    ("team_work_items work_intent column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'team_work_items' AND column_name = 'work_intent' AND data_type = 'jsonb';"),
    ("team_work_items execution_mode column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'team_work_items' AND column_name = 'execution_mode' AND data_type = 'text';"),
    ("team_work_items recovery_deadline_at column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'team_work_items' AND column_name = 'recovery_deadline_at' AND data_type = 'timestamp with time zone';"),
    ("team_interactions table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'team_interactions';"),
    ("team_status_events table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'team_status_events';"),
    ("team_status_events work_intent column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'team_status_events' AND column_name = 'work_intent' AND data_type = 'jsonb';"),
    ("team_status_events execution_mode column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'team_status_events' AND column_name = 'execution_mode' AND data_type = 'text';"),
    ("outcome_projects table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'outcome_projects';"),
    ("outcome_projects run_id text column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'outcome_projects' AND column_name = 'run_id' AND data_type = 'text';"),
    ("outcome_projects intent_proof_id text column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'outcome_projects' AND column_name = 'intent_proof_id' AND data_type = 'text';"),
    ("team_registry_entries table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'team_registry_entries';"),
    ("trigger_rules schedule columns", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'trigger_rules' AND column_name = 'trigger_kind';"),
    ("search_sources table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'search_sources';"),
    ("input_sources table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'input_sources';"),
    ("execution_dispatch_outbox table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'execution_dispatch_outbox';"),
    ("operator_sse_events table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'operator_sse_events';"),
    ("team_signal_receipts table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'team_signal_receipts';"),
    ("agent_catalogue profile_key column", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'agent_catalogue' AND column_name = 'profile_key';"),
    ("qa_fixture_scopes table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'qa_fixture_scopes';"),
    ("qa_fixture_resources table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'qa_fixture_resources';"),
    ("qa_fixture resource ownership index", "SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'uq_qa_fixture_resource_claim';"),
    ("purged QA fixture claims released", "SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM qa_fixture_resources r JOIN qa_fixture_scopes s ON s.id=r.scope_id WHERE s.status='purged');"),
    ("config_documents table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'config_documents';"),
    ("config_document_activations table", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'config_document_activations' AND column_name = 'kind';"),
    ("config_document_activation_history table", "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'config_document_activation_history' AND column_name = 'kind';"),
    ("config_document fixture ownership", "SELECT 1 FROM pg_constraint WHERE conname = 'chk_qa_fixture_resource_kind' AND pg_get_constraintdef(oid) LIKE '%config_document%';"),
    ("runtime_team_manifests table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'runtime_team_manifests';"),
    ("code_context_sources table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'code_context_sources';"),
    ("code_context_snapshots table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'code_context_snapshots';"),
    ("code_context_files table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'code_context_files';"),
    ("code_context_symbols table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'code_context_symbols';"),
    ("code_context_edges table", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'code_context_edges';"),
)
