package server

import "net/http"

// RegisterRoutes adds handlers to the mux.
func (s *AdminServer) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/admin/approvals", s.handleApprovals)
	mux.HandleFunc("/admin/approvals/", s.handleApprovalAction) // Trailing slash for ID parsing
	mux.HandleFunc("/agents", s.handleAgents)
	mux.HandleFunc("/healthz", s.handleHealth)

	// Stream API (guarded — Stream may be nil in degraded mode)
	if s.Stream != nil {
		mux.HandleFunc("/api/v1/stream", s.Stream.HandleStream)
	} else {
		mux.HandleFunc("/api/v1/stream", func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			http.Error(w, `{"error":"SSE stream handler not initialized — infrastructure offline"}`, http.StatusServiceUnavailable)
		})
	}

	mux.HandleFunc("/api/v1/memory/stream", s.GetMemoryStream)
	mux.HandleFunc("/api/v1/cognitive/infer", s.handleInfer)
	mux.HandleFunc("/api/v1/cognitive/config", s.HandleCognitiveConfig)
	mux.HandleFunc("/api/v1/cognitive/matrix", s.HandleCognitiveConfig) // Alias: UI calls /matrix
	mux.HandleFunc("GET /api/v1/cognitive/status", s.HandleCognitiveStatus)
	mux.HandleFunc("PUT /api/v1/cognitive/profiles", s.HandleUpdateProfiles)
	mux.HandleFunc("PUT /api/v1/cognitive/providers/{id}", s.HandleUpdateProvider)
	mux.HandleFunc("/api/v1/chat", s.HandleChat)

	mux.HandleFunc("POST /api/v1/council/{member}/chat", s.HandleCouncilChat)
	mux.HandleFunc("GET /api/v1/council/members", s.HandleListCouncilMembers)

	mux.HandleFunc("/api/v1/user/me", s.HandleMe)
	mux.HandleFunc("/api/v1/teams", s.HandleTeams)
	mux.HandleFunc("GET /api/v1/teams/detail", s.HandleTeamsDetail)
	mux.HandleFunc("/api/v1/user/settings", s.HandleUserSettings)
	mux.HandleFunc("/api/v1/settings/user", s.HandleUserSettings)
	mux.HandleFunc("GET /api/v1/groups", s.HandleListGroups)
	mux.HandleFunc("GET /api/v1/groups/monitor", s.HandleGroupMonitor)
	mux.HandleFunc("POST /api/v1/groups", s.HandleCreateGroup)
	mux.HandleFunc("PUT /api/v1/groups/{id}", s.HandleUpdateGroup)
	mux.HandleFunc("PATCH /api/v1/groups/{id}/status", s.HandleUpdateGroupStatus)
	mux.HandleFunc("GET /api/v1/groups/{id}/outputs", s.HandleGroupOutputs)
	mux.HandleFunc("POST /api/v1/groups/{id}/broadcast", s.HandleGroupBroadcast)

	mux.HandleFunc("GET /api/v1/missions", s.handleListMissions)
	mux.HandleFunc("GET /api/v1/missions/{id}", s.handleGetMission)
	mux.HandleFunc("PUT /api/v1/missions/{id}/agents/{name}", s.handleUpdateMissionAgent)
	mux.HandleFunc("DELETE /api/v1/missions/{id}/agents/{name}", s.handleDeleteMissionAgent)
	mux.HandleFunc("DELETE /api/v1/missions/{id}", s.handleDeleteMission)

	mux.HandleFunc("/api/v1/provision/draft", s.HandleProvisionDraft)
	mux.HandleFunc("/api/v1/provision/deploy", s.HandleProvisionDeploy)
	mux.HandleFunc("/api/v1/registry/templates", func(w http.ResponseWriter, r *http.Request) {
		if r.Method == "GET" {
			s.handleListTemplates(w, r)
		} else if r.Method == "POST" {
			s.handleRegisterTemplate(w, r)
		} else {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		}
	})
	mux.HandleFunc("POST /api/v1/teams/{id}/connectors", s.handleInstallConnector)
	mux.HandleFunc("GET /api/v1/teams/{id}/wiring", s.handleGetWiring)

	mux.HandleFunc("POST /api/v1/intent/negotiate", s.handleIntentNegotiate)
	mux.HandleFunc("POST /api/v1/intent/commit", s.handleIntentCommit)
	mux.HandleFunc("POST /api/v1/intent/confirm-action", s.HandleConfirmAction)
	mux.HandleFunc("POST /api/v1/intent/cancel-action", s.HandleCancelAction)
	mux.HandleFunc("GET /api/v1/audit", s.handleListAuditLog)
	mux.HandleFunc("GET /api/v1/templates", s.handleListTemplatesAPI)
	mux.HandleFunc("GET /api/v1/conversation-templates", s.HandleListConversationTemplates)
	mux.HandleFunc("POST /api/v1/conversation-templates", s.HandleCreateConversationTemplate)
	mux.HandleFunc("GET /api/v1/conversation-templates/{id}", s.HandleGetConversationTemplate)
	mux.HandleFunc("PATCH /api/v1/conversation-templates/{id}", s.HandleUpdateConversationTemplate)
	mux.HandleFunc("POST /api/v1/conversation-templates/{id}/instantiate", s.HandleInstantiateConversationTemplate)
	mux.HandleFunc("GET /api/v1/organizations", s.handleListOrganizations)
	mux.HandleFunc("POST /api/v1/organizations", s.handleCreateOrganization)
	mux.HandleFunc("GET /api/v1/organizations/{id}/home", s.handleGetOrganizationHome)
	mux.HandleFunc("PATCH /api/v1/organizations/{id}/ai-engine", s.handleUpdateOrganizationAIEngine)
	mux.HandleFunc("GET /api/v1/organizations/{id}/output-model-routing", s.handleGetOrganizationOutputModelRouting)
	mux.HandleFunc("PATCH /api/v1/organizations/{id}/output-model-routing", s.handleUpdateOrganizationOutputModelRouting)
	mux.HandleFunc("PATCH /api/v1/organizations/{id}/response-contract", s.handleUpdateResponseContract)
	mux.HandleFunc("PATCH /api/v1/organizations/{id}/departments/{departmentId}/ai-engine", s.handleUpdateDepartmentAIEngine)
	mux.HandleFunc("PATCH /api/v1/organizations/{id}/departments/{departmentId}/agent-types/{agentTypeId}/ai-engine", s.handleUpdateAgentTypeAIEngine)
	mux.HandleFunc("PATCH /api/v1/organizations/{id}/departments/{departmentId}/agent-types/{agentTypeId}/response-contract", s.handleUpdateAgentTypeResponseContract)
	mux.HandleFunc("POST /api/v1/organizations/{id}/workspace/actions", s.handleTeamLeadGuidedAction)
	mux.HandleFunc("GET /api/v1/organizations/{id}/automations", s.handleListAutomations)
	mux.HandleFunc("GET /api/v1/organizations/{id}/loop-activity", s.handleListLoopActivity)
	mux.HandleFunc("GET /api/v1/organizations/{id}/learning-insights", s.handleListLearningInsights)
	mux.HandleFunc("POST /api/v1/internal/organizations/{id}/loops/{loopId}/trigger", s.handleTriggerLoop)
	mux.HandleFunc("GET /api/v1/internal/organizations/{id}/loops/results", s.handleListLoopResults)
	mux.HandleFunc("GET /api/v1/intent/proof/{id}", s.handleGetIntentProof)
	mux.HandleFunc("POST /api/v1/intent/seed/symbiotic", s.handleSymbioticSeed)

	mux.HandleFunc("GET /api/v1/telemetry/compute", s.HandleTelemetry)
	mux.HandleFunc("/api/v1/trust/threshold", s.HandleTrustThreshold)
	mux.HandleFunc("GET /api/v1/homepage", s.HandleHomepageConfig)
	mux.HandleFunc("GET /api/v1/memory/search", s.HandleMemorySearch)
	mux.HandleFunc("GET /api/v1/search/status", s.HandleSearchStatus)
	mux.HandleFunc("POST /api/v1/search", s.HandleSearch)
	mux.HandleFunc("GET /api/v1/memory/sitreps", s.HandleListSitReps)
	mux.HandleFunc("/api/v1/memory/deployment-context", s.HandleDeploymentContext)
	mux.HandleFunc("/api/v1/memory/temp", s.HandleTempMemory)
	mux.HandleFunc("GET /api/v1/sensors", s.HandleSensors)
	mux.HandleFunc("GET /api/v1/comms/providers", s.HandleCommsProviders)
	mux.HandleFunc("POST /api/v1/comms/send", s.HandleCommsSend)
	mux.HandleFunc("POST /api/v1/comms/inbound/{provider}", s.HandleCommsInbound)

	mux.HandleFunc("/api/v1/proposals", s.HandleProposals)
	mux.HandleFunc("POST /api/v1/proposals/{id}/approve", s.HandleProposalApprove)
	mux.HandleFunc("POST /api/v1/proposals/{id}/reject", s.HandleProposalReject)

	mux.HandleFunc("POST /api/v1/mcp/install", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusForbidden)
		w.Write([]byte(`{"error":"Raw MCP install disabled. Use POST /api/v1/mcp/library/install with a curated server name."}`))
	})
	mux.HandleFunc("GET /api/v1/mcp/servers", s.handleMCPList)
	mux.HandleFunc("DELETE /api/v1/mcp/servers/{id}", s.handleMCPDelete)
	mux.HandleFunc("POST /api/v1/mcp/servers/{id}/tools/{tool}/call", s.handleMCPToolCall)
	mux.HandleFunc("GET /api/v1/mcp/tools", s.handleMCPToolsList)
	mux.HandleFunc("GET /api/v1/mcp/activity", s.handleMCPActivity)
	mux.HandleFunc("GET /api/v1/mcp/library", s.handleMCPLibrary)
	mux.HandleFunc("POST /api/v1/mcp/library/inspect", s.handleMCPLibraryInspect)
	mux.HandleFunc("POST /api/v1/mcp/library/install", s.handleMCPLibraryInstall)
	mux.HandleFunc("POST /api/v1/mcp/library/apply", s.handleMCPLibraryApply)

	mux.HandleFunc("GET /api/v1/governance/policy", s.handleGetPolicy)
	mux.HandleFunc("PUT /api/v1/governance/policy", s.handleUpdatePolicy)
	mux.HandleFunc("GET /api/v1/governance/pending", s.handleGetPendingApprovals)
	mux.HandleFunc("POST /api/v1/governance/resolve/{id}", s.handleResolveApproval)

	mux.HandleFunc("GET /api/v1/catalogue/agents", s.handleListCatalogue)
	mux.HandleFunc("POST /api/v1/catalogue/agents", s.handleCreateCatalogue)
	mux.HandleFunc("PUT /api/v1/catalogue/agents/{id}", s.handleUpdateCatalogue)
	mux.HandleFunc("DELETE /api/v1/catalogue/agents/{id}", s.handleDeleteCatalogue)
	mux.HandleFunc("GET /api/v1/artifacts", s.handleListArtifacts)
	mux.HandleFunc("GET /api/v1/artifacts/{id}", s.handleGetArtifact)
	mux.HandleFunc("GET /api/v1/artifacts/{id}/download", s.handleDownloadArtifact)
	mux.HandleFunc("POST /api/v1/artifacts", s.handleStoreArtifact)
	mux.HandleFunc("PUT /api/v1/artifacts/{id}/status", s.handleUpdateArtifactStatus)
	mux.HandleFunc("POST /api/v1/artifacts/{id}/save", s.handleSaveArtifactToFolder)

	mux.HandleFunc("GET /api/v1/exchange/fields", s.handleListExchangeFields)
	mux.HandleFunc("GET /api/v1/exchange/schemas", s.handleListExchangeSchemas)
	mux.HandleFunc("GET /api/v1/exchange/channels", s.handleListExchangeChannels)
	mux.HandleFunc("GET /api/v1/exchange/threads", s.handleListExchangeThreads)
	mux.HandleFunc("POST /api/v1/exchange/threads", s.handleCreateExchangeThread)
	mux.HandleFunc("GET /api/v1/exchange/items", s.handleListExchangeItems)
	mux.HandleFunc("POST /api/v1/exchange/items", s.handleCreateExchangeItem)
	mux.HandleFunc("GET /api/v1/exchange/search", s.handleSearchExchangeItems)

	mux.HandleFunc("GET /api/v1/brains", s.HandleListBrains)
	mux.HandleFunc("PUT /api/v1/brains/{id}/toggle", s.HandleToggleBrain)
	mux.HandleFunc("PUT /api/v1/brains/{id}/policy", s.HandleUpdateBrainPolicy)
	mux.HandleFunc("POST /api/v1/brains", s.HandleAddBrain)
	mux.HandleFunc("PUT /api/v1/brains/{id}", s.HandleUpdateBrain)
	mux.HandleFunc("DELETE /api/v1/brains/{id}", s.HandleDeleteBrain)
	mux.HandleFunc("POST /api/v1/brains/{id}/probe", s.HandleProbeBrain)

	mux.HandleFunc("GET /api/v1/context/snapshots", s.HandleListSnapshots)
	mux.HandleFunc("POST /api/v1/context/snapshot", s.HandleCreateSnapshot)
	mux.HandleFunc("GET /api/v1/context/snapshots/{id}", s.HandleGetSnapshot)
	mux.HandleFunc("GET /api/v1/mission-profiles", s.HandleListMissionProfiles)
	mux.HandleFunc("POST /api/v1/mission-profiles", s.HandleCreateMissionProfile)
	mux.HandleFunc("PUT /api/v1/mission-profiles/{id}", s.HandleUpdateMissionProfile)
	mux.HandleFunc("DELETE /api/v1/mission-profiles/{id}", s.HandleDeleteMissionProfile)
	mux.HandleFunc("POST /api/v1/mission-profiles/{id}/activate", s.HandleActivateMissionProfile)

	mux.HandleFunc("GET /api/v1/runs", s.handleListRuns)
	mux.HandleFunc("GET /api/v1/runs/{id}/events", s.handleGetRunEvents)
	mux.HandleFunc("GET /api/v1/runs/{id}/chain", s.handleGetRunChain)
	mux.HandleFunc("GET /api/v1/triggers", s.HandleListTriggers)
	mux.HandleFunc("POST /api/v1/triggers", s.HandleCreateTrigger)
	mux.HandleFunc("PUT /api/v1/triggers/{id}", s.HandleUpdateTrigger)
	mux.HandleFunc("DELETE /api/v1/triggers/{id}", s.HandleDeleteTrigger)
	mux.HandleFunc("POST /api/v1/triggers/{id}/toggle", s.HandleToggleTrigger)
	mux.HandleFunc("GET /api/v1/triggers/{id}/history", s.HandleTriggerHistory)

	mux.HandleFunc("GET /api/v1/services/status", s.HandleServicesStatus)
	mux.HandleFunc("GET /api/v1/host/status", s.HandleHostStatus)
	mux.HandleFunc("GET /api/v1/host/actions", s.HandleHostActions)
	mux.HandleFunc("POST /api/v1/host/actions/{id}/invoke", s.HandleInvokeHostAction)
	mux.HandleFunc("GET /api/v1/runs/{id}/conversation", s.HandleGetRunConversation)
	mux.HandleFunc("GET /api/v1/conversations/{session_id}", s.HandleGetSessionConversation)
	mux.HandleFunc("POST /api/v1/runs/{id}/interject", s.HandleRunInterject)

	mux.HandleFunc("GET /api/v1/inception/contracts", s.HandleInceptionContracts)
	mux.HandleFunc("GET /api/v1/inception/recipes", s.HandleListInceptionRecipes)
	mux.HandleFunc("GET /api/v1/inception/recipes/search", s.HandleSearchInceptionRecipes)
	mux.HandleFunc("GET /api/v1/inception/recipes/{id}", s.HandleGetInceptionRecipe)
	mux.HandleFunc("POST /api/v1/inception/recipes", s.HandleCreateInceptionRecipe)
	mux.HandleFunc("PATCH /api/v1/inception/recipes/{id}/quality", s.HandleUpdateRecipeQuality)

	mux.HandleFunc("GET /api/v1/mcp/toolsets", s.handleListToolSets)
	mux.HandleFunc("POST /api/v1/mcp/toolsets", s.handleCreateToolSet)
	mux.HandleFunc("PUT /api/v1/mcp/toolsets/{id}", s.handleUpdateToolSet)
	mux.HandleFunc("DELETE /api/v1/mcp/toolsets/{id}", s.handleDeleteToolSet)
}
